[package]
name = "stm32f3-dma"
version = "0.1.0"
edition = "2021"
authors = ["Renode Research"]

[dependencies]
cortex-m.workspace = true
cortex-m-rt.workspace = true
panic-halt.workspace = true
stm32f3xx-hal.workspace = true
stm32f3-common = { path = "../stm32f3-common" }
